CREATE TABLE IF NOT EXISTS create_articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title STRING, body TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);